### ISSUE TITLE
Create encoders and an EBCDIC record writer

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/cobrix#186]
## Background
Currently, Cobrix can be used only for reading EBCDIC data. Sometimes it is useful to be able to write EBCDIC records as well, for instance, to send EBCDIC-encoded messages to MQ. 
Currently, Cobrix has only EBCDIC decoders.

## Feature
Implement EBCDIC encoders that can be used to create binary records according to formats specified in a copybook.

## Subtasks
This is a big task. Here is a more detailed list of what is needed:
Encoders:
- [ ] Binary encoders from JVM integral types to IBM formats
- [ ] BCD encoders from JVM numeric types to IBM BCD formats
- [ ] Floating-point encoders from JVM floats and doubles IBM floating-point formats
- [ ] Encoders from JVM numeric types to IBM DISPLAY formats
- [ ] Encoders from JVM strings to IBM EBCDIC strings

Record writer:
- [ ] Given a record data structure and a parsed copybook, record writer should create a record as a binary array and fill it with record data according to the copybook.

**Comment by bhasi10** [comment]
Hi Ruslan
I am looking at an use case where I want to write back into EBCDIC file.Any update on when this enhancement would be complete.!

**Comment by yruslan** [comment]
Sorry, I can't provide any timelines at the moment.
